/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class', // Enable class-based dark mode
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#b4cbc7",
        "secondary-container": "#fe9e72",
        "outline-variant": "#c2c8c6",
        "on-secondary-fixed-variant": "#76320f",
        "outline": "#727877",
        "on-tertiary-fixed-variant": "#444937",
        "surface-dim": "#dadada",
        "inverse-primary": "#b4cbc7",
        "surface": "#f9f9f9",
        "error": "#ba1a1a",
        "on-secondary-container": "#773310",
        "on-error-container": "#93000a",
        "background": "#f9f9f9",
        "tertiary": "#252a1a",
        "on-tertiary-fixed": "#191d0e",
        "on-surface": "#1a1c1c",
        "secondary-fixed-dim": "#ffb596",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-container": "#97aeaa",
        "on-secondary": "#ffffff",
        "secondary": "#944925",
        "primary-fixed": "#d0e7e3",
        "inverse-on-surface": "#f1f1f1",
        "tertiary-container": "#3b402f",
        "surface-variant": "#e2e2e2",
        "surface-tint": "#4d635f",
        "inverse-surface": "#2f3131",
        "primary": "#172c29",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-low": "#f3f3f3",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#424847",
        "on-primary-fixed-variant": "#364b48",
        "primary-container": "#2d423f",
        "tertiary-fixed-dim": "#c4c9b1",
        "on-background": "#1a1c1c",
        "surface-bright": "#f9f9f9",
        "on-primary-fixed": "#091f1d",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#360f00",
        "on-tertiary-container": "#a7ac95",
        "on-error": "#ffffff",
        "tertiary-fixed": "#e0e5cc",
        "surface-container-highest": "#e2e2e2",
        "secondary-fixed": "#ffdbcd"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Manrope"],
        "label": ["Manrope"],
        "sans": ["Manrope", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      boxShadow: {
        'soft': '0 2px 8px rgba(0, 0, 0, 0.03)',
        'medium': '0 4px 16px rgba(0, 0, 0, 0.05)',
        'strong': '0 8px 24px rgba(0, 0, 0, 0.08)',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
