---
kind: pipeline
type: docker
name: sipi-ci-cd

platform:
  os: linux
  arch: arm64

clone:
  disable: true

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: clone
    image: alpine/git
    environment:
      TOKEN:
        from_secret: gitea_token
    commands:
      - git clone http://ajjimenezr:$TOKEN@gitea:3000/ajjimenezr/sipi.git .
      - git checkout $DRONE_COMMIT

  - name: install-backend
    image: node:20-alpine
    commands:
      - node --version
      - npm --version
      - ls -la backend/
      - cat backend/package.json | head -20
      - cd backend
      - npm ci 2>&1 || (echo "npm ci failed" && cat npm-debug.log 2>/dev/null || true && exit 1)

  - name: build-backend
    image: node:20-alpine
    commands:
      - cd backend && npm run build

  - name: build-frontend
    image: node:20-alpine
    commands:
      - cd frontend && npm ci && npx vite build

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 192.168.100.35
      username: ajjimenezr
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd ~/raspylab/production/sipi/app
        - git pull origin main
        - cd backend && npm ci --production && npm run build
        - sudo systemctl restart sipi
