---
kind: pipeline
type: docker
name: sipi-ci-cd

platform:
  os: linux
  arch: arm64

clone:
  disable: true

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: clone-and-build
    image: node:20-alpine
    environment:
      TOKEN:
        from_secret: gitea_token
    commands:
      - apk add --no-cache git
      - git clone http://ajjimenezr:$TOKEN@gitea:3000/ajjimenezr/sipi.git .
      - git checkout $DRONE_COMMIT
      - echo "=== Building Backend ==="
      - cd backend && npm ci && npm run build
      - echo "=== Building Frontend ==="
      - cd ../frontend && npm ci && npx vite build
      - echo "=== Build Complete ==="

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: deploy_host
      username:
        from_secret: deploy_username
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd ~/raspylab/production/sipi/app
        - git pull origin main
        - echo "=== Installing Backend Dependencies (with devDependencies for build) ==="
        - cd backend && npm ci
        - echo "=== Cleaning Failed Migrations (if any) ==="
        - mysql -u root sipi_db -e "DELETE FROM _prisma_migrations WHERE migration_name IN ('20250121200000_phase1_contact_security_softdelete', '20250121210000_phase2_academic_periods_capacity_enrollments', '20250121220000_phase3_careers_subjects', '20250121230000_phase4_personal_academic_info', '20250121240000_phase5_history_documents', '20251121235731_test');" || true
        - echo "=== Applying Database Migrations ==="
        - npx prisma migrate deploy
        - npx prisma generate
        - echo "=== Building Backend ==="
        - npm run build
        - echo "=== Installing Production Dependencies Only ==="
        - npm ci --omit=dev
        - echo "=== Building Frontend ==="
        - cd ../frontend && npm ci && npx vite build
        - echo "=== Copying Frontend to Public ==="
        - cd ../backend && rm -rf public/* public/.* 2>/dev/null || true
        - cp -r ../frontend/dist/* public/
        - echo "=== Restarting Service ==="
        - sudo systemctl restart sipi
        - echo "✅ Deploy completed successfully!"
