---
kind: pipeline
type: docker
name: sipi-ci-cd

platform:
  os: linux
  arch: arm64

clone:
  disable: true

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: clone
    image: alpine/git
    environment:
      TOKEN:
        from_secret: gitea_token
    commands:
      - git clone http://ajjimenezr:$TOKEN@gitea:3000/ajjimenezr/sipi.git .
      - git checkout $DRONE_COMMIT
      - ls -la
      - ls -la backend/ | head -10

  - name: install-backend
    image: node:20-alpine
    commands:
      - pwd
      - ls -la
      - echo "Node version:"
      - node --version
      - echo "NPM version:"
      - npm --version
      - echo "Checking backend directory:"
      - ls -la backend/
      - echo "Checking package.json:"
      - test -f backend/package.json && echo "package.json exists" || echo "package.json NOT FOUND"
      - test -f backend/package-lock.json && echo "package-lock.json exists" || echo "package-lock.json NOT FOUND"
      - echo "Starting npm ci..."
      - cd backend
      - npm ci --verbose 2>&1 | head -100 || (echo "=== npm ci FAILED ===" && cat npm-debug.log 2>/dev/null || cat .npm/_logs/*-debug.log 2>/dev/null || echo "No debug logs found" && exit 1)

  - name: build-backend
    image: node:20-alpine
    commands:
      - cd backend && npm run build

  - name: build-frontend
    image: node:20-alpine
    commands:
      - cd frontend && npm ci && npx vite build

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 192.168.100.35
      username: ajjimenezr
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd ~/raspylab/production/sipi/app
        - git pull origin main
        - cd backend && npm ci --production && npm run build
        - sudo systemctl restart sipi
