---
kind: pipeline
type: docker
name: sipi-ci-cd

platform:
  os: linux
  arch: arm64

clone:
  disable: true

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: clone-and-build
    image: node:20-alpine
    environment:
      TOKEN:
        from_secret: gitea_token
    commands:
      - apk add --no-cache git
      - git clone http://ajjimenezr:$TOKEN@gitea:3000/ajjimenezr/sipi.git .
      - git checkout $DRONE_COMMIT
      - echo "=== Building Backend ==="
      - cd backend && npm ci && npm run build
      - echo "=== Building Frontend ==="
      - cd ../frontend && npm ci && npx vite build
      - echo "=== Build Complete ==="

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 192.168.100.35
      username: ajjimenezr
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd ~/raspylab/production/sipi/app
        - git pull origin main
        - cd backend && npm ci --production && npm run build
        - sudo systemctl restart sipi
