---
kind: pipeline
type: docker
name: sipi-ci-cd

platform:
  os: linux
  arch: arm64

clone:
  disable: true

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: clone
    image: alpine/git
    environment:
      TOKEN:
        from_secret: gitea_token
    commands:
      - pwd
      - git clone http://ajjimenezr:$TOKEN@gitea:3000/ajjimenezr/sipi.git .
      - git checkout $DRONE_COMMIT
      - ls -la
      - ls -la backend/ || echo "No backend dir"

  - name: debug-workspace
    image: alpine
    commands:
      - pwd
      - ls -la
      - ls -la backend/ || echo "No backend dir after clone"

  - name: install-backend
    image: node:20-alpine
    commands:
      - pwd
      - ls -la
      - cd backend && npm ci --prefer-offline

  - name: build-backend
    image: node:20-alpine
    commands:
      - cd backend && npm run build

  - name: build-frontend
    image: node:20-alpine
    commands:
      - cd frontend && npm ci --prefer-offline && npx vite build

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 192.168.100.35
      username: ajjimenezr
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd ~/raspylab/production/sipi/app
        - git pull origin main
        - cd backend && npm ci --production && npm run build
        - sudo systemctl restart sipi
