---
kind: pipeline
type: docker
name: sipi-ci-cd

# CRÍTICO: Especificar arquitectura ARM64 para Raspberry Pi
platform:
  os: linux
  arch: arm64

# Clone manual para usar token de autenticación
clone:
  disable: true

trigger:
  branch:
    - main
  event:
    - push

steps:
  # Paso 1: Clone con autenticación
  - name: clone
    image: alpine/git
    environment:
      GITEA_TOKEN:
        from_secret: gitea_token
    commands:
      - git clone http://ajjimenezr:$GITEA_TOKEN@gitea:3000/ajjimenezr/sipi.git .
      - git checkout $DRONE_COMMIT
      - echo "Cloned commit $DRONE_COMMIT"

  # Paso 2: Instalar dependencias del backend
  - name: install-backend
    image: node:20-alpine
    commands:
      - cd backend
      - npm ci --prefer-offline
      - echo "Backend dependencies installed"

  # Paso 3: Build del backend (TypeScript → JavaScript)
  - name: build-backend
    image: node:20-alpine
    commands:
      - cd backend
      - npm run build
      - echo "Backend build completed"

  # Paso 4: Instalar y build del frontend
  - name: build-frontend
    image: node:20-alpine
    commands:
      - cd frontend
      - npm ci --prefer-offline
      - npx vite build
      - echo "Frontend build completed"

  # Paso 5: Deploy a producción via SSH
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 192.168.100.35
      username: ajjimenezr
      key:
        from_secret: ssh_key
      port: 22
      script:
        - echo "Starting deployment..."
        - cd ~/raspylab/production/sipi/app
        - git pull origin main
        - cd backend && npm ci --production && npm run build
        - cp -r ../frontend/dist ./public 2>/dev/null || true
        - sudo systemctl restart sipi
        - echo "Deployment completed!"

  # Paso 6: Verificar que el servicio está corriendo
  - name: healthcheck
    image: alpine
    commands:
      - apk add --no-cache curl
      - sleep 5
      - curl -f http://192.168.100.35:3001/health || exit 1
      - echo "Health check passed!"

---
# Pipeline para Pull Requests (solo build, sin deploy)
kind: pipeline
type: docker
name: sipi-pr-check

platform:
  os: linux
  arch: arm64

clone:
  disable: true

trigger:
  event:
    - pull_request

steps:
  - name: clone
    image: alpine/git
    environment:
      GITEA_TOKEN:
        from_secret: gitea_token
    commands:
      - git clone http://ajjimenezr:$GITEA_TOKEN@gitea:3000/ajjimenezr/sipi.git .
      - git fetch origin +refs/pull/${DRONE_PULL_REQUEST}/head:
      - git checkout FETCH_HEAD
      - echo "Cloned PR #$DRONE_PULL_REQUEST"

  - name: install-and-build
    image: node:20-alpine
    commands:
      - cd backend && npm ci && npm run build
      - cd ../frontend && npm ci && npx vite build
      - echo "PR build check passed!"
