---
kind: pipeline
type: docker
name: sipi-ci-cd

platform:
  os: linux
  arch: arm64

clone:
  disable: true

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: clone-and-build
    image: node:20-alpine
    environment:
      TOKEN:
        from_secret: gitea_token
    commands:
      - apk add --no-cache git
      - git clone http://ajjimenezr:$TOKEN@gitea:3000/ajjimenezr/sipi.git .
      - git checkout $DRONE_COMMIT
      - echo "=== Building Backend ==="
      - cd backend && npm ci && npm run build
      - echo "=== Building Frontend ==="
      - cd ../frontend && npm ci && npx vite build
      - echo "=== Build Complete ==="

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: deploy_host
      username:
        from_secret: deploy_username
      key:
        from_secret: ssh_key
      port: 22
      script:
        - set -e  # Fallar rápido en cualquier error
        - set -o pipefail  # Capturar errores en pipes
        - cd ~/raspylab/production/sipi/app
        - git pull origin main || { echo "❌ Error en git pull"; exit 1; }
        - echo "=== Installing Backend Dependencies (with devDependencies for build) ==="
        - cd backend && npm ci
        - echo "=== Applying Database Migrations ==="
        - npx prisma migrate deploy
        - npx prisma generate
        - echo "=== Building Backend ==="
        - npm run build
        - echo "=== Installing Production Dependencies Only ==="
        - npm ci --omit=dev
        - echo "=== Building Frontend ==="
        - cd ../frontend && npm ci && npx vite build
        - echo "=== Copying Frontend to Public ==="
        - cd ../backend && rm -rf public/* public/.* 2>/dev/null || true
        - cp -r ../frontend/dist/* public/
        - echo "=== Checking service status before restart ==="
        - sudo systemctl is-active sipi || echo "⚠️  Service was not active"
        - echo "=== Restarting Service ==="
        - sudo systemctl restart sipi
        - echo "=== Waiting for service to start ==="
        - sleep 5
        - echo "=== Verifying service is active ==="
        - sudo systemctl is-active sipi || { echo "❌ Service failed to start"; exit 1; }
        - echo "=== Verifying service health ==="
        - |
          for i in {1..10}; do
            if curl -f http://localhost:3001/health > /dev/null 2>&1; then
              echo "✅ Service is healthy"
              exit 0
            fi
            echo "⏳ Waiting for service... ($i/10)"
            sleep 2
          done
          echo "❌ Service health check failed after 20 seconds"
          exit 1
        - echo "✅ Deploy completed successfully!"
